#!/bin/bash
echo "Inside the db-scripts"
psql << EOF
CREATE DATABASE $POSTGRES_DB;
CREATE USER $POSTGRES_USER WITH PASSWORD $POSTGRES_PASSWORD;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB to $POSTGRES_USER;
EOF